model = "gpt-4.1"
model_provider = "openai-chat-completions"

[model_providers.openai-chat-completions]
name = "GitHub"
env_key = "OPENAI_API_KEY"
base_url = "https://models.github.ai/inference"
wire_api = "chat"
