name: ci

on:
  push:
  pull_request:

permissions:
  contents: read
  models: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: |
          npm install -g @openai/codex

      - run: |
          codex --version

      - name: test
        env:
          OPENAI_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          codex exec --profile config.toml --full-auto "hello"

      - name: Call AI model
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl "https://models.github.ai/inference/chat/completions" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -d '{
              "messages": [
                  {
                    "role": "user",
                    "content": "Explain the concept of recursion."
                  }
              ],
              "model": "openai/gpt-4o"
            }'
